version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

volumes:
  pg_data:
